title:              Your Average Digital Existential Chautauqua
email:              cajohnst1@gmail.com
description:        A mood board turned public
author:             Carter Johnston
baseurl:            ""
url:                "https://cajohnst.github.io"

# Social Profiles
twitter_username:   thacarterxciv
github_username:    cajohnst
facebook_username:
instagram_username:   thacarterxciv
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:    # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
